app = "tilastokaappari"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

[[mounts]]
  source = "tilastokaappari_data"
  destination = "/app/data"
  
[env]
  GUNICORN_WORKERS = "1"  # Vain yksi worker
  GUNICORN_TIMEOUT = "30"
  GUNICORN_MAX_REQUESTS = "50"  # Uudelleenkäynnistys joka 50. pyyntö

# Muistirajoitukset
[resources]
  memory = "512"  # Määritä muistimäärä MB-yksiköissä (vähintään 512MB)
