app = "tilastokaappari"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

[env]
  PORT = "8080"
  FLY_APP_NAME = "tilastokaappari"
  
[[mounts]]
  source = "tilastokaappari_data"  # Käytä täsmälleen tätä muotoa
  destination = "/app/data"
