app = "sinun-sovelluksesi-nimi"  # Anna uniikki nimi

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "data_volume"
  destination = "/app/data"
